r2dbc:
  datasources:
    default:
      url: r2dbc:mysql://127.0.0.1:3306/micronaut-aws-lambda-rest-sample?useSSL=false&characterEncoding=UTF-8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: passw0rd
      schema-generate: NONE
      dialect: MYSQL
flyway:
  datasources:
    default:
      enabled: true
      default-schema: micronaut-aws-lambda-rest-sample
      url: jdbc:mysql://127.0.0.1:3306/?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: passw0rd
redis:
  uri: redis://127.0.0.1:6379
javamail:
  authentication:
    username: ${SMTP_USERNAME:''}
    password: ${SMTP_PASSWORD:''}
  properties:
    mail:
      smtp:
        host: 127.0.0.1
        port: 1025
logger:
  levels:
    io.micronaut.data.query: DEBUG

application:
  fileUploadLocation: build/sample
