micronaut:
  application:
    name: micronaut-aws-lambda-rest-sample
  server:
    context-path: /api
  security:
    endpoints.login.path: /auth/login
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
              jws-algorithm: HS256
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - pattern: /api/swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /api/swagger/**
        access:
          - isAnonymous()
  data:
    pageable:
      size-parameter-name: perpage
  email:
    from:
      email: 'test@example.com'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
flyway:
  datasources:
    default:
      enabled: false
jackson:
  serialization:
    writeDatesAsTimestamps: false
